version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
    groups:
      runtime:
        dependency-type: production
        patterns: ["*"]
      development:
        dependency-type: development
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore
    groups:
      actions:
        patterns: ["*"]
